---
apiVersion: v1
kind: Secret
metadata:
  name: keyfactor-secret-example
  namespace: istio-system
type: Opaque
stringData:
  # Name of certificate authorization
  caName: ""

  # Using for authentication header
  authToken: ""

  # Certificate Template for enroll the new one: Default is Istio
  caTemplate: "Istio"

  # ApiKey from Api Setting
  appKey: ""
  